version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: fshama-erp
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        networks:
            - app-network

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fshama_db
            MYSQL_ROOT_PASSWORD: 
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
